[package]
name = "toto_memorial"
version = "0.1.0"
edition = "2024"

[lints.rust]
unused_parens = "allow"


[dependencies.maud]
version = "0.27"

[dependencies.image]
version = "0.25"

[dependencies.ffmpeg-next]
version = "7.1"

[dependencies.rand]
version = "0.9"
